//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// EACL
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const EACL_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "collateralWrappers_", internalType: "address[]", type: "address[]" }],
    stateMutability: "nonpayable",
  },
  { type: "error", inputs: [], name: "InvalidAuction" },
  { type: "error", inputs: [], name: "InvalidBid" },
  { type: "error", inputs: [], name: "InvalidClaim" },
  { type: "error", inputs: [], name: "InvalidLiquidation" },
  { type: "error", inputs: [], name: "InvalidParameters" },
  { type: "error", inputs: [], name: "InvalidToken" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "collateralToken", internalType: "address", type: "address", indexed: true },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256", indexed: true },
      { name: "bidder", internalType: "address", type: "address", indexed: false },
      { name: "amount", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "AuctionBid",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "collateralToken", internalType: "address", type: "address", indexed: true },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256", indexed: true },
      { name: "quantity", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "AuctionCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "collateralToken", internalType: "address", type: "address", indexed: true },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256", indexed: true },
      { name: "winner", internalType: "address", type: "address", indexed: false },
      { name: "proceeds", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "AuctionEnded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "collateralToken", internalType: "address", type: "address", indexed: true },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256", indexed: true },
      { name: "endTime", internalType: "uint64", type: "uint64", indexed: false },
    ],
    name: "AuctionExtended",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "collateralToken", internalType: "address", type: "address", indexed: true },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256", indexed: true },
      { name: "endTime", internalType: "uint64", type: "uint64", indexed: false },
    ],
    name: "AuctionStarted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "proceeds", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "LiquidationEnded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "source", internalType: "address", type: "address", indexed: true },
      { name: "liquidationContextHash", internalType: "bytes32", type: "bytes32", indexed: true },
      { name: "currencyToken", internalType: "address", type: "address", indexed: false },
      { name: "collateralToken", internalType: "address", type: "address", indexed: false },
      { name: "auctionCount", internalType: "uint16", type: "uint16", indexed: false },
    ],
    name: "LiquidationStarted",
  },
  {
    type: "function",
    inputs: [],
    name: "IMPLEMENTATION_VERSION",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "auctionDuration",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32" },
      { name: "collateralToken", internalType: "address", type: "address" },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "auctions",
    outputs: [
      {
        name: "",
        internalType: "struct EnglishAuctionCollateralLiquidator.Auction",
        type: "tuple",
        components: [
          { name: "quantity", internalType: "uint256", type: "uint256" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "highestBidder", internalType: "address", type: "address" },
          { name: "highestBid", internalType: "uint256", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32" },
      { name: "collateralToken", internalType: "address", type: "address" },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "bid",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "liquidationHash", internalType: "bytes32", type: "bytes32" },
      { name: "collateralToken", internalType: "address", type: "address" },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256" },
      { name: "liquidationContext", internalType: "bytes", type: "bytes" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "auctionDuration_", internalType: "uint64", type: "uint64" },
      { name: "timeExtensionWindow_", internalType: "uint64", type: "uint64" },
      { name: "timeExtension_", internalType: "uint64", type: "uint64" },
      { name: "minimumBidBasisPoints_", internalType: "uint64", type: "uint64" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "currencyToken", internalType: "address", type: "address" },
      { name: "collateralToken", internalType: "address", type: "address" },
      { name: "collateralTokenId", internalType: "uint256", type: "uint256" },
      { name: "collateralWrapperContext", internalType: "bytes", type: "bytes" },
      { name: "liquidationContext", internalType: "bytes", type: "bytes" },
    ],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "liquidationHash", internalType: "bytes32", type: "bytes32" }],
    name: "liquidations",
    outputs: [
      {
        name: "",
        internalType: "struct EnglishAuctionCollateralLiquidator.Liquidation",
        type: "tuple",
        components: [
          { name: "source", internalType: "address", type: "address" },
          { name: "currencyToken", internalType: "address", type: "address" },
          { name: "collateralToken", internalType: "address", type: "address" },
          { name: "auctionCount", internalType: "uint16", type: "uint16" },
          { name: "liquidationContextHash", internalType: "bytes32", type: "bytes32" },
          { name: "proceeds", internalType: "uint256", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "minimumBidBasisPoints",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "timeExtension",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "timeExtensionWindow",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
] as const;
